### ISSUE TITLE
App failed to build with the plugin

### ISSUE THREAD

**Issue by Loky31** [solar2d/com.solar2d-plugin.yodo1#1]
Hello,
It appears that building with Solar2D fails when adding this plugin.
Here is what is in the console : 
 FAILURE: Build failed with an exception.
00:33:39.223  
00:33:39.223  * What went wrong:
00:33:39.223  Execution failed for task ':App:checkReleaseAarMetadata'.
00:33:39.223  > Could not resolve all files for configuration ':App:releaseRuntimeClasspath'.
00:33:39.223     > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223       Required by:
00:33:39.223           project :App
00:33:39.223        > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223           > Could not get resource 'https://dl.bintray.com/yodo1/android-sdk/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'.
00:33:39.223              > Could not GET 'https://dl.bintray.com/yodo1/android-sdk/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'. Received status code 403 from server: Forbidden
00:33:39.223        > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223           > Could not get resource 'https://applovin.bintray.com/Android-Adapter-SDKs/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'.
00:33:39.223              > Could not GET 'https://applovin.bintray.com/Android-Adapter-SDKs/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'. Received status code 403 from server: Forbidden
00:33:39.223        > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223           > Could not get resource 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'.
00:33:39.223              > Could not GET 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'. Received status code 403 from server: Forbidden
00:33:39.223        > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223           > Could not get resource 'https://chartboostmobile.bintray.com/Chartboost/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'.
00:33:39.223              > Could not GET 'https://chartboostmobile.bintray.com/Chartboost/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'. Received status code 403 from server: Forbidden
00:33:39.223        > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223           > Could not get resource 'https://fyber.bintray.com/marketplace/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'.
00:33:39.223              > Could not GET 'https://fyber.bintray.com/marketplace/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'. Received status code 403 from server: Forbidden
00:33:39.223        > Could not resolve com.yodo1:advert-gp:3.13.0.
00:33:39.223           > Could not get resource 'https://dl.bintray.com/mintegral-official/mintegral_ad_sdk_android_for_oversea/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'.
00:33:39.223              > Could not GET 'https://dl.bintray.com/mintegral-official/mintegral_ad_sdk_android_for_oversea/com/yodo1/advert-gp/3.13.0/advert-gp-3.13.0.pom'. Received status code 403 from server: Forbidden
00:33:39.223  
00:33:39.223  * Try:
00:33:39.223  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
00:33:39.223  
00:33:39.223  * Get more help at https://help.gradle.org

Any help or correction possible?

**Comment by Shchvova** [comment]
This should work. It seems like connectivity issues.
